import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import classes from "./Studentslife.module.scss";
import MiniLayoutRight from "../../components/MiniLayoutRight/MiniLayoutRight";
import StudentCarousel from "../../components/StudentCarousel/StudentCarousel";
let links = [
  { title: "All Categories", href: "/" },
  { title: "Admission", href: "/" },
  { title: "Application", href: "/" },
  { title: "Competition", href: "/" },
  { title: "Courses", href: "/" },
  { title: "Events", href: "/" },
];

const Studentslife = () => {
  return (
    <>
      <Head>
        <title>Students Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MiniLayoutRight title={"Students Life"} links={links}>
        <div className={classes.body}>
          <StudentCarousel
            imgs={["student.png", "student.png", "student.png", "student.png"]}
          />
          <div className={classes.body__text}>
            <p>
              The spirituality and enlightenment department supervises all work
              done at the institute in this area. It brings into accord the
              principles stated in standard documents, generalizes an
              operational experience of departments, public organization and
              chairs in the spirituality sphere; preparing and publishing
              required scientifically – methodical instructions and literatures,
              carrying out various actions directed toward promoting spiritual
              maturity of students.
            </p>
            <h5>The types of events organized include the following:</h5>
            <ul>
              <li>
                Social (Teachers day, Comedy show, International Women’s day,
                Navruz)
              </li>
              <li>
                International Women’s day, Navruz) Intellectual (Zakovat club,
                Brain club, Workshop clubs)
              </li>
              <li> Sports (Football, Volleyball, Tennis, Chess cup)</li>
            </ul>
          </div>
        </div>
      </MiniLayoutRight>
    </>
  );
};

export const getStaticProps = async (context) => {
  const locale = context.locale;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
};

export default Studentslife;
