import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import classes from "./Admission.module.scss";
import MiniLayout from "../../components/MiniLayout/MiniLayout";
import Links from "../../components/MiniNavigation/Links";
import steps from "./data.json";
import Features from "../../components/Features/Features";
import Image from "next/image";
import img from "../../public/media/images/admission.png";
const Studentslife = () => {
  return (
    <div className={classes.body}>
      <Head>
        <title>Admission</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MiniLayout links={Links.links2} title={"Admissions Process"}>
        <h1>
          Thank you for choosing Amity International school. Choosing the right
          school for your child is one of the most important decisions any
          parent will ever make.
        </h1>
        <h1>
          The admissions team will guide you, as our future parents, through a
          smooth student onboarding process.
        </h1>
        <div className={classes.img}>
          <Image alt={img} src={img} layout="fill" />
          <h1>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero
            asperiores dolor repellat nulla quos quidem repudiandae, quo earum,
            obcaecati nobis fugit consequuntur facere dolorem? Porro nobis
            blanditiis obcaecati voluptas officia?
          </h1>
        </div>
        <h2>How to apply</h2>
        <Features features={steps.apply} />
      </MiniLayout>
    </div>
  );
};

export const getStaticProps = async (context) => {
  const locale = context.locale;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
};

export default Studentslife;
