import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import classes from "./Alumni.module.scss";
import MiniLayout from "../../components/MiniLayout/MiniLayout";
import Links from "../../components/MiniNavigation/links.json";
import AppTabs from "../../components/muiCustom/AppTabs/AppTabs";
import data from "./data.json";
import Image from "next/image";

const Alumni = () => {
  return (
    <>
      <Head>
        <title>Alumni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MiniLayout links={Links.links} title="Alumni">
        <AppTabs>
          {data.map((dat, index) => (
            <div key={index} label={dat.tabName} className={classes.texts}>
              <Image
                width={"700"}
                height={"500"}
                src={`/media/images/${dat?.tabBody?.image}`}
              ></Image>
              <h1>{dat?.tabBody?.title}</h1>
              <p className={classes.desc}>{dat?.tabBody?.description}</p>
            </div>
          ))}
        </AppTabs>
      </MiniLayout>
    </>
  );
};

export const getStaticProps = async (context) => {
  const locale = context.locale;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
};

export default Alumni;
