import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import classes from "./Ourcampus.module.scss";
import data from "./data.json";
import MiniLayout from "../../components/MiniLayout/MiniLayout";
import Links from "../../components/MiniNavigation/links.json";
import Image from "next/image";
const Ourcampus = () => {
  const text = data.text;
  return (
    <>
      <Head>
        <title>Our Campus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MiniLayout links={Links.links} title="Our Campus">
        <div className={classes.texts}>
          {text.map((dat) => (
            <>
              <Image
                width={"700"}
                height={"500"}
                src={`/media/images/${dat.image}`}
              ></Image>
              <p>{dat.small}</p>
              <p>{dat.small}</p>
            </>
          ))}
        </div>
      </MiniLayout>
    </>
  );
};

export const getStaticProps = async (context) => {
  const locale = context.locale;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
};

export default Ourcampus;
