import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import BreadCrumb from "../../components/BreadCrumb/BreadCrumb";
import AppTabs from "../../components/muiCustom/AppTabs/AppTabs";
import CareerTable from "../../components/muiCustom/CareerTable/CareerTable";
import SimpleHeading from "../../components/SimpleHeading/SimpleHeading";
import classes from "./Career.module.scss";
import { dataCareer } from "./facedata/facedataPage";

export default function Career() {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>{t("AMITY || Career")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`container ${classes["career_top"]} `}>
        <BreadCrumb />
        <SimpleHeading hedingText={t("Career with Amity")} />
      </main>
      <div className={classes["tabs_wrapper"]}>
        <AppTabs border={true} className={"container"}>
          {dataCareer.map((data, i) => (
            <div key={i} label={data?.tabName}>
              <CareerTable rows={data?.tabBody} />
            </div>
          ))}
        </AppTabs>
      </div>
    </>
  );
}

export const getStaticProps = async (context) => {
  const locale = context.locale;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
};
