import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import classes from "./Internationalcampus.module.scss";
import MiniLayout from "../../components/MiniLayout/MiniLayout";
import Links from "../../components/MiniNavigation/links.json";
import data from "./data.json";
import SimpleHeading from "../../components/SimpleHeading";

import Image from "next/image";

const Internationalcampus = () => {
  const head = data.head;
  const body = data.body;

  return (
    <>
      <Head>
        <title>International Campus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MiniLayout links={Links.links} title="International Campus">
        <Image
          src={`/media/images/${head.image}`}
          width={"700"}
          height={"450"}
          alt={head.image}
        ></Image>
        <p style={{ padding: "10px 0" }}>{head.desc}</p>
        <p style={{ padding: "10px 0" }}>{head.desc}</p>

        {body.map((dat, index) => (
          <div key={index} className={classes.body}>
            <SimpleHeading left hedingText={dat.heading}></SimpleHeading>

            <h1>{dat.title}</h1>
            <p>{dat.desc}</p>

            <ul>
              {dat?.values?.map((dat2) => (
                <>
                  <li>{dat2}</li>
                </>
              ))}
            </ul>
          </div>
        ))}
      </MiniLayout>
    </>
  );
};

export const getStaticProps = async (context) => {
  const locale = context.locale;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
};

export default Internationalcampus;
