import Head from "next/head";
import SimpleAccordion from "../../components/Accordion/Accordion";
import BreadCrumb from "../../components/BreadCrumb";
import SimpleHeading from "../../components/SimpleHeading/SimpleHeading";
import classes from "./Faq.module.scss";
import data from "./data.json";
import { useTranslation } from "next-i18next";

export default function Faq() {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className={classes.bread}>
          <BreadCrumb />
        </div>
        <div className={classes.heading}>
          <SimpleHeading hedingText={t("Frequently Asked Questions")} />
        </div>

        <div className={classes.accardions}>
          {data.map((dat, idx) => (
            <SimpleAccordion key={idx} ques={t(dat.ques)} answ={t(dat.answ)} />
          ))}
        </div>
      </div>
    </>
  );
}
