import Head from "next/head";
import classes from "./Amityglobal.module.scss";
import BreadCrumb from "./../../components/BreadCrumb";
import SimpleHeading from "../../components/SimpleHeading";
import data from "../../fakedata/amityGlobal.json";
import Amityglobal from "./../../components/Amityglobal";

export default function AmityGlobal() {
  return (
    <>
      <Head>
        <title>Amity Global</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="page--blue">
        <div className={classes.body}>
          <BreadCrumb />
          <SimpleHeading white hedingText={"Amity Global"} />
          <div className={classes.body__cards}>
            {data.data.map((card, idx) => (
              <div key={idx} className={classes.body__card}>
                <Amityglobal
                  img={card.img}
                  title={card.title}
                  text={card.text}
                />
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
