import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { useTranslation } from "next-i18next";
import data from "../fakedata/home.json";
import MainSlider from "../components/MainSlider/MainSlider";
import classes from "../styles/pages/Home.module.scss";
import SimpleCard from "../components/SimpleCard/SimpleCard";
import SimpleHeading from "../components/SimpleHeading";
import HomeNews from "../components/HomeNews/HomeNews";
import InfoCard from "../components/InfoCard/InfoCard";
import Image from "next/image";
import HomeContact from "../components/HomeContact/HomeContact";
const settings = {
  dots: false,
  arrows: false,
  autoplay: true,
  infinite: true,
  speed: 1000,
  slidesToShow: 5,
  autoplaySpeed: 2000,
  slidesToScroll: 1,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 4,
        slidesToScroll: 1,
      },
    },
    {
      breakpoint: 700,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 1,
      },
    },
    {
      breakpoint: 500,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 1,
      },
    },
    {
      breakpoint: 400,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1,
      },
    },
  ],
};
export default function Home() {
  const { t } = useTranslation();

  return (
    <div className={classes["home"]}>
      <Head>
        <title>Amity Tashkent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page--white">
        <div className="sld">
          <MainSlider data={data.mainSlider} />
        </div>
        <div className={classes["home__programs"]}>
          <div className="container">
            <SimpleHeading primary hedingText={t("PROGRAM & Academics")} />
            <div className={classes["home__programs__cards"]}>
              {data.programs.map((program, idx) => (
                <SimpleCard
                  key={idx}
                  backImg={program.img}
                  title={program.title}
                  link={program.link}
                />
              ))}
            </div>
          </div>
        </div>
        <div className={classes["home__news"]}>
          <div className="container">
            <HomeNews />
          </div>
        </div>
        <div className={classes["home__info"]}>
          <div className="container">
            {data.info.map((info, idx) => (
              <InfoCard
                className={classes["home__info__card"]}
                key={idx}
                title={info.title}
                text={info.text}
                primary={info.primary}
                bgImg={`media/images/${info.img}`}
              />
            ))}
          </div>
        </div>
      </div>
      <div className={classes["home__partners"]}>
        <Slider {...settings}>
          {data.partners.map((partner, idx) => (
            <div key={idx} className={classes["home__partners__image"]}>
              <Image
                src={`/media/images/${partner}`}
                layout="fill"
                alt="partner"
              />
            </div>
          ))}
        </Slider>
      </div>
      <div className={classes["home__contact"]}>
        <HomeContact />
      </div>
    </div>
  );
}

export const getStaticProps = async (context) => {
  const locale = context.locale;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
};
